CREATE TABLE EVENTS
(
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  EVENT_NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(150),
  DATE_BEGIN TIMESTAMP NOT NULL,
  DATE_END TIMESTAMP NOT NULL,
  ADDRESS VARCHAR(50)
)