CREATE TABLE USERS
(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    MOBILE_NUMBER VARCHAR(25),
    EMAIL VARCHAR(75),
    ADDRESS VARCHAR(50)
)
