SELECT evts.ID, evts.EVENT_NAME, evts.DESCRIPTION, evts.ADDRESS, evts.DATE_BEGIN, evts.DATE_END
FROM (SELECT EVENT_ID as eid FROM BINDS WHERE USER_ID=?) AS eres
  INNER JOIN
  (SELECT ID, EVENT_NAME, DESCRIPTION, ADDRESS, DATE_BEGIN, DATE_END FROM EVENTS WHERE DATE_BEGIN > CURRENT_TIMESTAMP) AS evts
    ON eid=evts.ID